version: '3.8'

services:
  AisMsgParse:
    build:
      context: https://github.com/NikitaSerkov/AisMsgParse.git
    container_name: ais-monitor
    volumesll:
      - ./conf.ini:/root/conf.ini
      - ./ais-archive:/root/Archive
    restart: unless-stopped
