version: '3.8'

services:
  ais-monitor:
    build:
      context: https://github.com/NikitaSerkov/AisMsgParse.git#main
    container_name: ais-monitor
    volumes:
      - ./conf.ini:/root/conf.ini
      - ./ais-archive:/root/Archive
    restart: unless-stopped


